<a href="https://colab.research.google.com/github/YulianaVega1/DataVisualization/blob/main/DataStructure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2.3 Sciling

To access one or several elements of the object.

In [13]:
# extract the first element
import numpy as np

## Column vector
print(a[0,0])

NameError: ignored

In [ ]:
print(b[0,0])

## Matrix 
print(M[0,0])

In [ ]:
# extract the last element
print(a[-1,0])
print(b[0,-1])
print(M[-1,-1])

In [ ]:
# Extract a subset

## Column vector
print(a[0:2])

## Row Vector

print(b[0,0:2])

## matrix
print(M[0:2,0:2])

# 2.4 Method

In [14]:
# ZEROS

z1 = np.zeros(4)
print(z1)

[0. 0. 0. 0.]


In [15]:
z2 = np.zeros((3,2))
print(z2)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# ONES
o1 = np.ones(4)
print(o1)


o2 = np.ones((3,2))
print(o2)

Another creation options

In [ ]:
# full

f = np.full((3,2),5)
print(f)

In [ ]:
# linear sequence

np.arange(6)
np.arange(23,33)
np.arange(23,33,0.5)

In [ ]:
#  Linear space (dividir en partes iguales)

np.linspace(15,90,6)

## 2.5. Random Numbers


In [ ]:
# a single value between 0 and 1 
np.random.seed(123)
np.random.rand()

In [16]:
# example - toss a coin
if np.random.rand() < 0.5:
  print('head')
else:
  print('tails')

tails


In [ ]:
if np.random.rand() < 0.25:
  print('You win')
else:
  print('You lose')

In [25]:
# Two heads in a row

ft = np.random.rand()

if ft < 0.5:
  print('The first toss is head')
else:
  print('The first toss is tails')

st = np.random.rand()

if st < 0.5:
  print('The second toss is head')
else:
  print('The second toss is tails')

if ft < 0.5 and st < 0.5:
  print('You win:3')
else:
  print('You lose :c')

The first toss is head
The second toss is head
You win:3


In [2]:
# One dimensional array
np.random.rand(5)

array([0.9808932 , 0.39591257, 0.22037022, 0.29255541, 0.78493867])

In [4]:
# Matrix

np.random.rand(6,2)

array([[0.23838781, 0.30456679],
       [0.27297659, 0.65627008],
       [0.42531011, 0.17228667],
       [0.4431855 , 0.81155326],
       [0.69338471, 0.70065125],
       [0.12005705, 0.72363113]])

### Uniform distribution (a,b)

In [8]:
# Single value

np.random.uniform(low = -10, high = 0)

-9.053985954637279

In [9]:
# One dimensional array

np.random.uniform(low = -10, high = 0, size = 7)

array([-2.51761116, -2.14276772, -2.07535258, -3.98263445, -6.8967188 ,
       -8.26399295, -9.19957215])

In [12]:
# Matrix

np.random.uniform(low = -10, high = 0, size = (5,4))

array([[-6.71172827, -8.52188671, -0.13147654, -4.54445934],
       [-5.74678927, -1.42165312, -9.87172428, -8.49214635],
       [-4.97037847, -1.24136577, -4.84687147, -9.66721273],
       [-6.55444074, -7.81058475, -5.5953887 , -7.31430018],
       [-6.30392044, -7.9534879 , -0.03646431, -4.23711207]])

In [38]:
# Exercise
meh = 60
m = 80
wow = 100

np.random.uniform(low = meh, high = wow, size = (5,3))

array([[91.84271327, 69.14627579, 62.92617319],
       [78.13557928, 90.94049339, 91.25040718],
       [62.80763906, 94.68957327, 88.32223715],
       [87.04794681, 78.47125924, 94.88883333],
       [84.60819022, 89.4478109 , 89.32300939]])

### Exercise

Simulate the sale of a shop according to

| Scenario | Prob | Sales |
|----------|------|-------|
| Bad      | 25%  |60     |
|Normal    | 50%  |80     |
|Wow       | 75%  |100    |

In [46]:
# Solution

for i in range(1,6):
  tmp = np.random.rand()
  if tmp <0.25:
    print('Day:',1,'scenario: Bad', 'units sold: 60')
  elif tmp >0.75:
    print('Day','scenario: wow', 'units sold: 100')
  

scenario: wow units sold: 100
scenario: Bad units sold: 60
scenario: Bad units sold: 60
scenario: wow units sold: 100
scenario: Bad units sold: 60
