<a href="https://colab.research.google.com/github/YulianaVega1/DataVisualization/blob/main/Phyton_variable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. What is a variable?**

A variable is a container, in the sense that it *stores* values.

# **Declaration**

In [ ]:
# Example

a = 2.54
print(a)
round(a)

2.54


3

In [ ]:
#Example
nm=8.5245645
pl= 0
pf =7
print('The aproximation of', nm, 'with:')
print('decimals', 'Results')
for i in range(pl,pf+1): print(i, '\t', round(nm,i)) 


The aproximation of 8.5245645 with:
decimals Results
0 	 9.0
1 	 8.5
2 	 8.52
3 	 8.525
4 	 8.5246
5 	 8.52456
6 	 8.524565
7 	 8.5245645


In [ ]:
# Example 

x = y = z = 45

print(x,y,z)

45 45 45


In [ ]:
# Example remplace value

z = 17

# **3. Delete and clear**

In [ ]:
# Example delete

del x, y

In [ ]:
# Example clear

%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


# **4. Naming

## 4.1 conditions and restriction

In [ ]:
# Example - always a name of variable must start with a letter

age = 18



## 4.2 Best practices

* Case sensitive

In [ ]:
# Example 

Age = 15

AGE = 41

# Sug: Always use lower case (minuscula)

* Compound name

In [ ]:
#  Example 

price_jean = 150000



# **5. Data types**

## 5.1 integers
## 5.2 Float


# **Parenthesis:** A trick

In [ ]:
# Example - set up 

w += -3

print(w)

2


# 5.3 Text

In [ ]:
# Example

name = 'universidad de la salle'
print(name)

universidad de la salle


In [ ]:
name[0]

'u'

In [ ]:
name[-2]

'l'

In [ ]:
name[0:12]

'universidad '

In [ ]:
name.split()[0]

'universidad'

Example 3 vector

In [2]:
M = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(M)
print(M, shape)

NameError: ignored

# 2.3 Sciling

To access one or several elements of the object.


In [25]:
# extract the first element
import numpy as np

## Column vector
print(a[0,0])

NameError: ignored

In [5]:
print(b[0,0])

## Matrix 
print(M[0,0])

NameError: ignored

In [6]:
# extract the last element
print(a[-1,0])
print(b[0,-1])
print(M[-1,-1])

NameError: ignored

In [93]:
# Extract a subset

## Column vector
print(a[0:2])

## Row Vector

print(b[0,0:2])

## matrix
print(M[0:2,0:2])

NameError: ignored

# 2.4 Method



In [92]:
# ZEROS

z1 = np.zeros(4)
print(z1)

[0. 0. 0. 0.]


In [48]:
z2 = np.zeros((3,2))
print(z2)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [49]:
# ONES
o1 = np.ones(4)
print(o1)


o2 = np.ones((3,2))
print(o2)

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


Another creation options

In [47]:
# full

f = np.full((3,2),5)
print(f)

[[5 5]
 [5 5]
 [5 5]]


In [46]:
# linear sequence

np.arange(6)
np.arange(23,33)
np.arange(23,33,0.5)

array([23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. , 27.5, 28. ,
       28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5])

In [45]:
#  Linear space (dividir en partes iguales)

np.linspace(15,90,6)

array([15., 30., 45., 60., 75., 90.])

## 2.5. Random Numbers



In [44]:
# a single value between 0 and 1 
np.random.seed(123)
np.random.rand()

0.6964691855978616

In [73]:
# example - toss a coin
if np.random.rand() < 0.5:
  print('head')
else:
  print('tails')

tails


In [90]:
if np.random.rand() < 0.25:
  print('You win')
else:
  print('You lose')

You win


In [127]:
# Two heads in a row

ft = np.random.rand()

if ft < 0.5:
  print('The first toss is head')
else:
  print('The first toss is tails')

st = np.random.rand()

if st < 0.5:
  print('The second toss is head')
else:
  print('The second toss is tails')

if ft < 0.5 and st < 0.5:
  print('You win:3')
else:
  print('You lose :c')

The first toss is head
The second toss is head
You win:3
